'''
Created on Sep 1, 2020

@author: admin
'''

SECONDS = 1
MINUTES = 60 * SECONDS
HOURS = 60 * MINUTES
DAYS = 24 * HOURS
MONTHS = 30 * DAYS
YEARS = 12 * MONTHS

SECONDS = 1
SEC_PER_MIN = 60 * SECONDS
SEC_PER_HOUR = 60 * SEC_PER_MIN
SEC_PER_DAY = 24 * SEC_PER_HOUR
SEC_PER_MONTH = 30 * SEC_PER_DAY
SEC_PER_YEAR = 12 * SEC_PER_MONTH
